# Generated by Django 5.2.7 on 2025-11-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(unique=True)),
                ("rss_feed_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrapingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_selector",
                    models.CharField(
                        help_text="Her bir yayın bloğunu kapsayan ana CSS seçici.",
                        max_length=255,
                    ),
                ),
                (
                    "title_selector",
                    models.CharField(
                        help_text="Başlığı içeren elementin CSS seçicisi.",
                        max_length=255,
                    ),
                ),
                (
                    "link_selector",
                    models.CharField(
                        help_text="Yayın linkini içeren 'a' etiketinin CSS seçicisi.",
                        max_length=255,
                    ),
                ),
                (
                    "description_selector",
                    models.CharField(
                        blank=True,
                        help_text="Açıklamayı içeren elementin CSS seçicisi.",
                        max_length=255,
                    ),
                ),
                (
                    "author_selector",
                    models.CharField(
                        blank=True,
                        help_text="Yazarı içeren elementin CSS seçicisi.",
                        max_length=255,
                    ),
                ),
                (
                    "website",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraping_rule",
                        to="core.website",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="core.website",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
