# Generated by Django 5.2.7 on 2025-11-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingrule",
            name="published_at_selector",
            field=models.CharField(
                blank=True,
                help_text="Yayın tarihini içeren elementin CSS seçicisi.",
                max_length=255,
            ),
        ),
    ]
